language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO='django>=1.6,<1.7'
  - DJANGO='django>=1.7,<1.8'
  - DJANGO='--pre django'
install:
  - psql -c 'CREATE DATABASE orderable' -U postgres;
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
script: "make test"
notifications:
  email: false
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO='django>=1.7,<1.8'
    - python: "3.4"
      env: DJANGO='django>=1.7,<1.8'
before_install:
  pip install codecov
after_success:
  codecov
